const zhTW = {
  locale: { label: '語言', enUS: 'English', zhTW: '繁體中文' },
  shell: { footer: '© 2026 Gallops Digital. 版權所有。' },
  common: {
    checking: '驗證中…', loading: '載入中…', password: '密碼', eventId: '活動 ID', logOut: '登出', cancel: '取消', optional: '選填', system: '系統',
    scheduled: '已排程', active: '進行中', ended: '已結束', archived: '已封存', waiting: '等候中', served: '已服務', left: '已離隊', removed: '已移除',
    person: '人', people: '人', noActivity: '沒有活動', event: '活動', status: '狀態', period: '期間', total: '總計', phone: '電話', message: '訊息', customer: '顧客', joined: '加入時間', action: '操作', view: '檢視'
  },
  branding: { logoAlt: '{name} 活動標誌', previewAlt: '{name} 標誌預覽' },
  lifecycle: { notOpen: '尚未開放', closed: '已關閉', opensAt: '{date}（香港時間）', closedAt: '{date}（香港時間）', closedNoDate: '活動存取期間已結束。' },
  errors: { accessDenied: '存取被拒', queueNotFound: '找不到隊伍', loadDashboard: '無法載入控制台', actionFailed: '操作失敗', joinFailed: '無法加入隊伍', leaveFailed: '無法離開隊伍', eventNotFound: '找不到活動', loadAdmin: '無法載入管理控制台', loadAdminData: '無法載入管理資料', loadEvent: '無法載入活動', loadArchived: '無法載入已封存活動', createEvent: '無法建立活動', editEvent: '無法編輯活動', archiveEvent: '無法封存活動', restoreEvent: '無法還原活動', invalidLogo: '請選擇不超過 2 MB 的 PNG、JPEG 或 WebP 圖片。', logoUploadAfterSave: '活動資料已儲存，但標誌上載失敗。你可以在編輯活動中重試。' },
  home: { eyebrow: 'NextQ · 活動營運', title: '工作人員管理員登入', intro: '請輸入供應商管理員提供的活動 ID 及密碼。', eventIdPlaceholder: '例如 megabox-summer-ab12', submit: '開啟活動控制台', customerHint: '顧客請使用活動工作人員分享的公開網址或 QR Code。' },
  staff: {
    dashboard: '工作人員管理控制台', queueOpens: '隊伍將於 {date}（香港時間）開放', scheduledHint: '工作人員管理員登入及隊伍操作會於開放時間啟用。', endedTitle: '此隊伍已結束', endedHint: '工作人員操作已停用，供應商管理員仍可查看顧客紀錄。', backLogin: '返回登入', protectedEvent: '受保護活動', access: '工作人員管理員存取', passwordHint: '請輸入供應商管理員設定的活動密碼。', unlock: '解鎖控制台', anotherEvent: '使用其他活動 ID', loading: '正在載入控制台…', waitingCount: '{count} {unit}等候中', callNext: '呼叫下一位', publicAccess: '顧客公開入口', publicHint: '將此公開網址或 QR Code 分享給顧客。', qrAlt: '顧客隊伍 QR Code', publicUrl: '顧客公開網址', copyUrl: '複製公開網址', downloadQr: '下載 QR Code', previewCustomer: '預覽顧客頁面', currentQueue: '目前隊伍', fifo: '先到先得', clearConfirm: '確定清空整條隊伍？', clearAll: '全部清除', empty: '目前沒有顧客等候', emptyHint: '分享 QR Code 讓顧客開始排隊。', removeConfirm: '確定移除 {name}？', remove: '移除'
  },
  customer: {
    loading: '正在載入隊伍…', queue: '顧客隊伍', queueOpens: '隊伍將於 {date}（香港時間）開放', scheduledHint: '目前尚未開放加入，請於開放時間後再返回。', endedTitle: '此隊伍已結束', endedNoDate: '存取期間已結束，新加入及原有等候票均已關閉。', endedWithDate: '存取期間已於 {date}（香港時間）結束，新加入及原有等候票均已關閉。', liveUpdates: '此瀏覽器會即時更新位置', position: '你的排隊位置', now: '現在', yourTurn: '現正輪到你', next: '下一位就是你', inLine: '你正在排隊', called: '現正輪到你，請於5分鐘到回到活動場地入場', statsLabel: '即時隊伍統計', peopleAhead: '前面人數', totalWaiting: '等候總數', ticket: '票號 #{id}', keepOpen: '請保持此頁開啟，位置會自動更新。', leaveConfirm: '確定離開此隊伍？', leave: '離開隊伍', join: '加入隊伍', waitingNow: '目前有 {count} {unit}等候', first: '成為第一位', joinHint: '加入後會立即顯示你的即時位置。', name: '你的姓名', namePlaceholder: '輸入你的姓名', phone: '電話號碼', phonePlaceholder: '+852 9123 4567', message: '訊息', messagePlaceholder: '告訴工作人員你的需要', joining: '加入中…', joinButton: '加入隊伍'
  },
  superAdmin: { checking: '正在驗證管理員存取…', restricted: '受限制區域', title: '供應商管理員存取', intro: '供應商管理員可建立、編輯、檢視及封存 MEGABOX 活動。', key: '供應商管理員金鑰', open: '開啟管理面板' },
  adminShell: { modules: '模組', adminModules: '管理員模組', close: '關閉', closeModules: '關閉模組', vendorAdmin: '供應商管理員', workspace: '工作區', overview: '總覽', events: '活動', audit: '稽核記錄', system: '系統', online: '系統在線', operational: '所有服務運作正常', live: '即時營運', refresh: '重新整理資料' },
  overview: { eyebrow: '營運控制台', title: '總覽', intro: '所有 MEGABOX 活動的即時健康狀態及活動。', systemOverview: '系統總覽', events: '活動', managed: '受管理活動', waitingNow: '目前等候', across: '所有活動合計', served: '已服務', completed: '已完成顧客', totalCustomers: '顧客總數', retained: '保留紀錄', scheduled: '已排程', notOpen: '尚未開放', active: '進行中', open: '可供存取', ended: '已結束', completedPeriod: '期間已完成', activeQueues: '進行中隊伍', activeHint: '目前有顧客等候的活動。', viewAll: '查看全部', queueWaiting: '{count} 人等候', noActive: '沒有進行中隊伍', recent: '最近活動', recentHint: '最新稽核事件。', openLog: '開啟記錄' },
  audit: { eyebrow: '合規與診斷', title: '稽核記錄', intro: '特殊權限存取及隊伍生命週期事件的唯增歷史。', count: '{count} 個事件', search: '搜尋事件', searchPlaceholder: '操作、執行者或活動', event: '活動', all: '所有活動', customer: '顧客 #{id}', none: '沒有相符的稽核事件' },
  systemPage: { eyebrow: '營運', title: '系統', intro: '此管理控制台的執行狀態及安全邊界。', operational: '運作正常', apiConnected: 'API 已連線', apiHint: '管理總覽及稽核端點正常回應。', ready: '就緒', dbReady: '資料庫就緒', dbHint: 'SQLite 歷史及唯增稽核資料可供使用。', records: '{count} 筆紀錄', auth: '管理員驗證', authHint: '伺服器端臨時金鑰及強化工作階段 Cookie。', protected: '已保護', cf: 'Cloudflare Access', cfHint: '外部身分允許清單保留作下一層安全邊界。', notEnabled: '未啟用', boundary: '營運邊界', boundaryHint: '公開顧客及工作人員隊伍路由與超級管理員工作區互相獨立。Cloudflare Access 只應保護此控制台及其管理 API 路由。' },
  queues: {
    noEnd: '沒有結束日期', eyebrow: '活動管理', title: '活動', intro: '供應商管理員負責建立、編輯、稽核及封存活動；工作人員管理員只操作進行中的隊伍。', count: '{count} 個活動', create: '建立活動', megabox: 'MEGABOX 活動', archivedHint: '已封存活動仍保留作除錯及稽核。', archivedCount: '已封存（{count}）', search: '搜尋活動', searchPlaceholder: '搜尋活動名稱或 ID', to: '至', noMatch: '沒有相符活動', noMatchHint: '請嘗試其他活動名稱或 ID。', loadingDetail: '正在載入活動詳情…', detail: '活動詳情', edit: '編輯活動', back: '返回活動', starts: '開始：{date}', ends: '結束：{date}', timeZone: '時區：{zone}', staffPage: '工作人員管理頁面', customerPage: '顧客公開頁面', countWaiting: '等候中', countServed: '已服務', countEnded: '已離隊／移除', countTotal: '總計', endedColumn: '結束時間', noHistory: '沒有顧客紀錄', restoreTitle: '還原已封存活動', archiveTitle: '封存活動', restoreHint: '按原有活動期間恢復存取，舊票不會重新開啟。', archiveHint: '顧客及工作人員管理員存取將停止，活動歷史會保留作稽核。', restore: '還原活動', vendorAdmin: '供應商管理員', pageSetup: '頁面設定', eventName: '活動名稱', eventNamePlaceholder: 'MEGABOX 週末活動', eventDescription: '活動描述', descriptionPlaceholder: '向顧客介紹活動內容及注意事項。', eventLogo: '活動標誌', logoHint: '支援 PNG、JPEG 或 WebP，最大 2 MB。', removeLogo: '移除標誌', staffPassword: '工作人員管理員密碼', passwordHint: '工作人員會使用產生的活動 ID 及此密碼登入 NextQ。', accessPeriod: '活動存取期間', eventStart: '活動開始', startNow: '立即開始', schedule: '排程', startDate: '開始日期及時間（香港）', endDate: '結束日期（選填，香港）', creating: '建立中…', editTitle: '編輯活動', newPassword: '新的工作人員管理員密碼', keepPassword: '留空以保留目前密碼', newStart: '新的開始日期及時間', newEnd: '新的結束日期', clearEnd: '清空以移除', saving: '儲存中…', save: '儲存活動', archiveQuestion: '封存活動？', archiveRouteHint: '顧客及工作人員管理員路由將停止，顧客歷史會保留。', typeConfirm: '輸入 {name} 以確認', archiving: '封存中…'
  },
  notFound: { title: '找不到頁面', hint: '此隊伍連結可能不正確。', back: '返回首頁' }
} as const;

export default zhTW;
